Fix request body for GET and HEAD methods
php-http/curl-client pull request #61
Opened 2019-11-05 09:59 UTC by grongor

There is no limitation in cURL that would prevent these methods to have a body. And without the body for these requests you are unable to use APIs that require it, such as https://docs.confluent.io/current/kafka-rest/api.html#get--consumers-(string-group_name)-instances-(string-instance)-offsets .

2019-12-27 11:01 UTC, dbu requested changes
i agree with not discarding the body.

2019-12-27 12:25 UTC, grongor commented on tests/Functional/HttpClientTestCase.php
> -    public function testSendRequest($httpMethod, $uri, array $httpHeaders, $requestBody): void
I didn't delete the test. I deleted an override, which skipped tests.

2020-01-02 09:11 UTC, dbu commented on tests/Functional/HttpClientTestCase.php
> -    public function testSendRequest($httpMethod, $uri, array $httpHeaders, $requestBody): void
oh, cool then!

2020-01-03 11:38 UTC, grongor commented on src/Client.php
> +                return $curlOptions;
I pushed a commit with some refactoring, I hope it's more to your liking.

2020-01-03 11:39 UTC, grongor commented on src/Client.php
> +                return $curlOptions;
Btw I didn't do this first time because I just wanted to keep the changes at minimum to simplify the review.

2020-01-04 11:59 UTC, dbu commented on src/Client.php
> +                return $curlOptions;
right, that is a good point. in the long run, i prefer readability over the small diff so thanks for having adjusted it.

2020-01-04 12:06 UTC, dbu approved these changes
thanks, this makes sense to me!

could you please add something to the CHANGELOG.md file to explain that GET with body is now supported?

@Nyholm do you agree as well, or any doubts or worries?

2020-01-04 12:07 UTC, Nyholm commented
I know that the intention is correct. The GET and HEAD requests can have bodies. Im not sure about the implementation because I dont know this client well enough. 

Can @mekras have a look?

2023-04-28 13:25 UTC, closed without merging